name: notifications

services:
  ntfy:
    image: binwiederhier/ntfy:v2.17@sha256:4768ca4ed07bf5ba0331f333bfccc541ba1594ed7fa5a7b0245763a581809344
    container_name: ntfy
    volumes:
      - data:/var/lib/ntfy
    environment:
      - TZ=America/New_York
      - NTFY_BASE_URL=https://ntfy.mattvperry.com/
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHEMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_ENABLE_LOGIN=true
      - NTFY_AUTH_USERS=${NTFY_AUTH_USERS}
      - NTFY_AUTH_TOKENS=${NTFY_AUTH_TOKENS}
      - NTFY_AUTH_ACCESS=api:*:rw
      - NTFY_REQUIRE_LOGIN=true
    command:
      - serve
    restart: unless-stopped

volumes:
  data:
