name: notifications

services:
  ntfy:
    image: binwiederhier/ntfy:v2.16@sha256:115357a63dd35e3d08ad03c93ade7d7eef63761726572b809da13f2999f1958f
    container_name: ntfy
    volumes:
      - data:/var/lib/ntfy
    environment:
      - TZ=America/New_York
      - NTFY_BASE_URL=https://ntfy.mattvperry.com/
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHEMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_ENABLE_LOGIN=true
      - NTFY_AUTH_USERS=${NTFY_AUTH_USERS}
      - NTFY_AUTH_TOKENS=${NTFY_AUTH_TOKENS}
      - NTFY_AUTH_ACCESS=api:*:rw
      - NTFY_REQUIRE_LOGIN=true
    command:
      - serve
    restart: unless-stopped

volumes:
  data:
